/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemaGestaoMerci.apresentacao;

import br.edu.ifnmg.sistemaGestaoMerci.entidade.Usuario;
import br.edu.ifnmg.sistemaGestaoMerci.excecao.CampoObrigatorioException;
import br.edu.ifnmg.sistemaGestaoMerci.excecao.SistemaGestaoException;
import br.edu.ifnmg.sistemaGestaoMerci.negocio.UsuarioBO;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Rayssa
 */
public class CadastroDeUsuarioForm extends javax.swing.JFrame {

    private Usuario usuario;
    private Usuario filtro;
    private List<Usuario> usuarios;
    private boolean usuarioEmEdicao;
    private ListagemUsuarioForm listagemUsuarioForm;

    /**
     * Creates new form CadastroVendaForm
     */
    public CadastroDeUsuarioForm() {
        usuario = new Usuario();

        initComponents();
    }

    CadastroDeUsuarioForm(Usuario usuarioSelecionado, ListagemUsuarioForm listagemUsuarioForm) {
        usuarioEmEdicao = true;
        usuario = usuarioSelecionado;
        this.listagemUsuarioForm = listagemUsuarioForm;
        initComponents();
        inicializarCamposTela();

    }

    public void inicializarCamposTela() {
        this.txtNome.setText(this.usuario.getNome());
        this.txtLogin.setText(this.usuario.getLogin());
        this.txtSenha.setText(this.usuario.getSenha());

        if (usuario.getGrupo().equals("GERENTE")) {
            chbGerente.setSelected(true);
        } else if (usuario.getGrupo().equals("CAIXEIRO")) {
            chbCaixeiro.setSelected(true);
        } else if (usuario.getGrupo().equals("GESTOR DE COMPRAS")) {
            chbGestorCompras.setSelected(true);
        } else if (usuario.getGrupo().equals("GESTOR DE ESTOQUE")) {
            chbGestorEstoque.setSelected(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoUsuario = new javax.swing.ButtonGroup();
        pnlDadosUsuario = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lblCampoObrigatorio = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        pnlGrupoUsuario = new javax.swing.JPanel();
        chbGerente = new javax.swing.JCheckBox();
        chbGestorEstoque = new javax.swing.JCheckBox();
        chbGestorCompras = new javax.swing.JCheckBox();
        chbCaixeiro = new javax.swing.JCheckBox();
        btnVoltar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setExtendedState(6);

        pnlDadosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Usuário"));

        lblNome.setText("Nome *:");

        lblLogin.setText("Login *:");

        lblSenha.setText("Senha *:");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaGestaoMerci/apresentacao/imagens/disk.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblCampoObrigatorio.setText("*Campos de preencimento obrigatório.");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        pnlGrupoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos De Usuário"));

        btnGrupoUsuario.add(chbGerente);
        chbGerente.setText("Gerente");

        btnGrupoUsuario.add(chbGestorEstoque);
        chbGestorEstoque.setText("Gestor De Estoque");

        btnGrupoUsuario.add(chbGestorCompras);
        chbGestorCompras.setText("Gestor De Compras");

        btnGrupoUsuario.add(chbCaixeiro);
        chbCaixeiro.setText("Caixeiro");

        javax.swing.GroupLayout pnlGrupoUsuarioLayout = new javax.swing.GroupLayout(pnlGrupoUsuario);
        pnlGrupoUsuario.setLayout(pnlGrupoUsuarioLayout);
        pnlGrupoUsuarioLayout.setHorizontalGroup(
            pnlGrupoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrupoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGrupoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGrupoUsuarioLayout.createSequentialGroup()
                        .addComponent(chbGerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbGestorCompras))
                    .addGroup(pnlGrupoUsuarioLayout.createSequentialGroup()
                        .addComponent(chbGestorEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbCaixeiro)))
                .addContainerGap())
        );
        pnlGrupoUsuarioLayout.setVerticalGroup(
            pnlGrupoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrupoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGrupoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbGerente)
                    .addComponent(chbGestorCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pnlGrupoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbGestorEstoque)
                    .addComponent(chbCaixeiro))
                .addContainerGap())
        );

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaGestaoMerci/apresentacao/imagens/arrow_left.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaGestaoMerci/apresentacao/imagens/zoom.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaGestaoMerci/apresentacao/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaGestaoMerci/apresentacao/imagens/cancel.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosUsuarioLayout = new javax.swing.GroupLayout(pnlDadosUsuario);
        pnlDadosUsuario.setLayout(pnlDadosUsuarioLayout);
        pnlDadosUsuarioLayout.setHorizontalGroup(
            pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGrupoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDadosUsuarioLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSenha)
                            .addComponent(lblLogin)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogin)
                            .addComponent(txtSenha)
                            .addComponent(txtNome)))
                    .addGroup(pnlDadosUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCampoObrigatorio)
                            .addGroup(pnlDadosUsuarioLayout.createSequentialGroup()
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDadosUsuarioLayout.setVerticalGroup(
            pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosUsuarioLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin))
                .addGap(10, 10, 10)
                .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlGrupoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosUsuarioLayout.createSequentialGroup()
                        .addComponent(lblCampoObrigatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (usuarioEmEdicao == false) {
            salvarUsuario();
        } else {
            editarUsuario();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void editarUsuario() {
        try {
            this.recuperarCamposTela();

            UsuarioBO usuarioBO = new UsuarioBO();
            usuarioBO.alterarUsuario(usuario);
            JOptionPane.showMessageDialog(this,
                    "Usuário alterado com sucesso!",
                    "Alteração de Usuário",
                    JOptionPane.INFORMATION_MESSAGE);
            this.limparCamposTela();
            listagemUsuarioForm.carregaTabelaUsuario();
            btnSalvar.setEnabled(false);

        } catch (SistemaGestaoException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Alteração de Usuário",
                    JOptionPane.ERROR_MESSAGE
            );
            btnSalvar.setEnabled(true);

        } catch (Exception e) {
            System.out.println("Erro inesperado! Informe a mensagem de erro ao administrador do sistema.");
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(
                    this,
                    "Erro inesperado! Informe o erro ao administrador do sistema",
                    "Alteração de Usuário",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void salvarUsuario() {
        try {
            this.recuperarCamposTela();

            UsuarioBO usuarioBO = new UsuarioBO();
            usuarioBO.inserirUsuario(usuario);
            JOptionPane.showMessageDialog(this,
                    "Usuário cadastrado com sucesso!",
                    "Cadastro de Usuário",
                    JOptionPane.INFORMATION_MESSAGE);
            this.limparCamposTela();
            btnSalvar.setEnabled(false);

        } catch (SistemaGestaoException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Cadastro de Usuário",
                    JOptionPane.ERROR_MESSAGE
            );
            btnSalvar.setEnabled(true);

        } catch (Exception e) {
            System.out.println("Erro inesperado! Informe a mensagem de erro ao administrador do sistema.");
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(
                    this,
                    "Erro inesperado! Informe o erro ao administrador do sistema",
                    "Cadastro de Usuário",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            // TODO add your handling code here:
            pesquisarUsuarioCadastrado();
        } catch (SistemaGestaoException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Pesquisa de Usuário",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            System.out.println("Erro inesperado! Informe a mensagem de erro ao administrador do sistema.");
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(
                    this,
                    "Erro inesperado! Informe o erro ao administrador do sistema",
                    "Pesquisa de Usuário",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:

        int resposta;
        String mensagem = "Deseja Cadastrar Usuário? ";
        String titulo = "Cadastro Novo Usuário";
        resposta = JOptionPane.showConfirmDialog(this, mensagem, titulo, JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_NO_OPTION) {
            CadastroDeUsuarioForm cadastroUsuario = new CadastroDeUsuarioForm();
            cadastroUsuario.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        this.excluirUsuarioPesquisado();
    }//GEN-LAST:event_btnExcluirActionPerformed
    private void excluirUsuarioPesquisado() {
        try {

            int resposta;
            String mensagem = "Deseja excluir Usuário? " + usuario.getLogin();
            String titulo = "Exclusão de Usuário";
            resposta = JOptionPane.showConfirmDialog(this, mensagem, titulo, JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_NO_OPTION) {
                UsuarioBO usuarioBo = new UsuarioBO();
                usuarioBo.removerUsuario(usuario);
                inicializarCamposTela();
                JOptionPane.showMessageDialog(this, "Usuário Excluido com sucesso!", "Pesquisa Exclusão de Usuário", JOptionPane.INFORMATION_MESSAGE);
                limparCamposTela();
            }
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Exclusão de Usuário ", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    private void pesquisarUsuarioCadastrado() throws SQLException {
        Usuario usuarioBuscado = new Usuario();
        usuarioBuscado.setLogin(txtLogin.getText().trim());

        UsuarioBO usuarioBO = new UsuarioBO();
        usuario = usuarioBO.pesquisarLoginCadastrado(usuarioBuscado);
        inicializarCamposTela();

    }

    private void limparCamposTela() {
        this.txtNome.setText("");
        this.txtLogin.setText("");
        this.txtSenha.setText("");
        if (chbCaixeiro.isSelected()) {
            this.chbCaixeiro.setSelected(false);
        } else if (chbGerente.isSelected()) {
            this.chbGerente.setSelected(false);
        } else if (chbGestorCompras.isSelected()) {
            this.chbGestorCompras.setSelected(false);
        } else {
            this.chbGestorEstoque.setSelected(false);
        }
    }

    private void recuperarCamposTela() throws ParseException {
        if (!txtNome.getText().trim().equals("")) {
            usuario.setNome(txtNome.getText().trim());
        } else {
            throw new CampoObrigatorioException();
        }
        if (!txtLogin.getText().trim().equals("")) {
            usuario.setLogin(txtLogin.getText().trim());
        } else {
            throw new CampoObrigatorioException();
        }
        if (!txtSenha.getText().trim().equals("")) {
            usuario.setSenha(txtSenha.getText().trim());
        } else {
            throw new CampoObrigatorioException();
        }
        if (chbCaixeiro.isSelected()) {
            usuario.setGrupo("CAIXEIRO");
        } else if (chbGerente.isSelected()) {
            usuario.setGrupo("GERENTE");
        } else if (chbGestorCompras.isSelected()) {
            usuario.setGrupo("GESTOR DE COMPRAS");
        } else if (chbGestorEstoque.isSelected()) {
            usuario.setGrupo("GESTOR DE ESTOQUE");
        } else {
            throw new CampoObrigatorioException();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeUsuarioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGrupoUsuario;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox chbCaixeiro;
    private javax.swing.JCheckBox chbGerente;
    private javax.swing.JCheckBox chbGestorCompras;
    private javax.swing.JCheckBox chbGestorEstoque;
    private javax.swing.JLabel lblCampoObrigatorio;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlDadosUsuario;
    private javax.swing.JPanel pnlGrupoUsuario;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
